[workspace]
resolver = "2"
members = [
    "crates/consensus",
    "crates/pal",
    "xtask",
]

[workspace.dependencies]
qash-consensus = { path = "crates/consensus", version = "0.1.0" }
qash-pal       = { path = "crates/pal",       version = "0.1.0" }

[profile.release]
opt-level     = 3
lto           = true
codegen-units = 1
panic         = "abort"

[profile.test]
opt-level = 1
