[package]
name = "qash"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[workspace]
members = [
  "crates/consensus",
  "crates/pal",
  "crates/vector-runner",
]

[dependencies]
qash-consensus = { path = "crates/consensus" }
qash-pal = { path = "crates/pal" }
sha3        = { version = "0.10", default-features = false }
blake3      = { version = "=1.5.5", default-features = false }
tiny-keccak = { version = "2",    features = ["k12"] }
sm3         = { version = "0.4",  default-features = false }
streebog    = { version = "0.10", default-features = false }

[[bin]]
name = "compute-genesis-hash"
path = "src/bin/compute_genesis_hash.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = true
debug-assertions = true
strip = true
